# Generated by Django 6.0.3 on 2026-04-15 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def add_user_field_if_missing(apps, schema_editor):
    idrequest_model = apps.get_model("idrequest", "IDRequest")
    table_name = idrequest_model._meta.db_table

    with schema_editor.connection.cursor() as cursor:
        columns = {
            column.name
            for column in schema_editor.connection.introspection.get_table_description(
                cursor, table_name
            )
        }

    if "user_id" in columns:
        return

    field = models.OneToOneField(
        on_delete=django.db.models.deletion.CASCADE,
        related_name="id_request",
        to=settings.AUTH_USER_MODEL,
    )
    field.set_attributes_from_name("user")
    schema_editor.add_field(idrequest_model, field)


def remove_user_field_if_present(apps, schema_editor):
    idrequest_model = apps.get_model("idrequest", "IDRequest")
    table_name = idrequest_model._meta.db_table

    with schema_editor.connection.cursor() as cursor:
        columns = {
            column.name
            for column in schema_editor.connection.introspection.get_table_description(
                cursor, table_name
            )
        }

    if "user_id" not in columns:
        return

    field = models.OneToOneField(
        on_delete=django.db.models.deletion.CASCADE,
        related_name="id_request",
        to=settings.AUTH_USER_MODEL,
    )
    field.set_attributes_from_name("user")
    schema_editor.remove_field(idrequest_model, field)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('idrequest', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    add_user_field_if_missing,
                    remove_user_field_if_present,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='idrequest',
                    name='user',
                    field=models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='id_request',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
