# Generated by Django 6.0.3 on 2026-04-06 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addevent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='alumni/events/'),
        ),
    ]
