# Generated by Django 6.0.3 on 2026-04-15 06:34

from django.db import migrations, models


def create_auditlog_table_if_missing(apps, schema_editor):
    from auditlogs.models import AuditLog as Model

    model = Model
    table_name = model._meta.db_table

    with schema_editor.connection.cursor() as cursor:
        tables = schema_editor.connection.introspection.table_names(cursor)

    if table_name in tables:
        return

    schema_editor.create_model(model)


def drop_auditlog_table_if_present(apps, schema_editor):
    from auditlogs.models import AuditLog as Model

    model = Model
    table_name = model._meta.db_table

    with schema_editor.connection.cursor() as cursor:
        tables = schema_editor.connection.introspection.table_names(cursor)

    if table_name not in tables:
        return

    schema_editor.delete_model(model)


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    create_auditlog_table_if_missing,
                    drop_auditlog_table_if_present,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="AuditLog",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("actor_email", models.EmailField(blank=True, max_length=254, null=True)),
                        ("actor_name", models.CharField(blank=True, max_length=150, null=True)),
                        ("actor_role", models.CharField(choices=[("admin", "Admin"), ("staff", "Staff"), ("id-staff", "ID Staff"), ("user", "User"), ("anonymous", "Anonymous"), ("system", "System")], default="anonymous", max_length=20)),
                        ("action", models.CharField(max_length=120)),
                        ("method", models.CharField(max_length=10)),
                        ("path", models.CharField(max_length=255)),
                        ("resource", models.CharField(blank=True, max_length=100, null=True)),
                        ("resource_id", models.CharField(blank=True, max_length=50, null=True)),
                        ("success", models.BooleanField(default=True)),
                        ("status_code", models.PositiveIntegerField(blank=True, null=True)),
                        ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                        ("user_agent", models.TextField(blank=True, null=True)),
                        ("details", models.JSONField(blank=True, default=dict)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                    ],
                    options={
                        "ordering": ["-created_at"],
                        "db_table": "user_auditlog",
                        "indexes": [
                            models.Index(fields=["-created_at"], name="user_auditl_created_566317_idx"),
                            models.Index(fields=["actor_role", "-created_at"], name="user_auditl_actor_r_7de8e2_idx"),
                            models.Index(fields=["action", "-created_at"], name="user_auditl_action_f9a284_idx"),
                        ],
                    },
                ),
            ],
        ),
    ]
