# Generated by Django 6.0.3 on 2026-04-15 06:34

import backend.storage
from django.db import migrations, models


def create_csv_upload_table_if_missing(apps, schema_editor):
    from alumnicsvupload.models import AlumniStudentCSVUpload as Model

    model = Model
    table_name = model._meta.db_table

    with schema_editor.connection.cursor() as cursor:
        tables = schema_editor.connection.introspection.table_names(cursor)

    if table_name in tables:
        return

    schema_editor.create_model(model)


def drop_csv_upload_table_if_present(apps, schema_editor):
    from alumnicsvupload.models import AlumniStudentCSVUpload as Model

    model = Model
    table_name = model._meta.db_table

    with schema_editor.connection.cursor() as cursor:
        tables = schema_editor.connection.introspection.table_names(cursor)

    if table_name not in tables:
        return

    schema_editor.delete_model(model)


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    create_csv_upload_table_if_missing,
                    drop_csv_upload_table_if_present,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="AlumniStudentCSVUpload",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("title", models.CharField(blank=True, max_length=150, null=True)),
                        ("csv_file", models.FileField(storage=backend.storage.AssetFolderCloudinaryStorage(), upload_to="alumni-students/csv/")),
                        ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                    ],
                    options={
                        "ordering": ["-uploaded_at"],
                        "db_table": "alumnistudent_alumnistudentcsvupload",
                    },
                ),
            ],
        ),
    ]
