# Generated by Django 6.0.3 on 2026-03-31 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('job_description', models.TextField()),
                ('industry', models.CharField(max_length=100)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('internship', 'Internship'), ('contract', 'Contract')], max_length=20)),
                ('work_setup', models.CharField(choices=[('on_site', 'On-site'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('salary_range', models.CharField(blank=True, max_length=100, null=True)),
                ('required_skills', models.TextField(blank=True, null=True)),
                ('education_requirement', models.CharField(max_length=200)),
                ('experience_level', models.CharField(choices=[('entry', 'Entry-level'), ('mid', 'Mid-level'), ('senior', 'Senior')], max_length=20)),
                ('application_deadline', models.DateField()),
                ('application_link_or_email', models.CharField(max_length=300)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='jobs/')),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
            ],
            options={
                'ordering': ['-date_posted'],
            },
        ),
    ]
