# Generated by Django 6.0.3 on 2026-04-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0003_alter_jobpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='jobs/'),
        ),
    ]
