# Generated by Django 6.0.3 on 2026-04-15 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('age', models.PositiveIntegerField()),
                ('role', models.CharField(choices=[('user', 'User'), ('staff', 'Staff'), ('id-staff', 'ID Staff'), ('admin', 'Admin')], default='user', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('alumni_id', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('course', models.CharField(blank=True, max_length=100, null=True)),
                ('year_graduate', models.PositiveIntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=150, null=True)),
                ('contact_num', models.CharField(blank=True, max_length=20, null=True)),
                ('current_job', models.CharField(blank=True, max_length=150, null=True)),
                ('company', models.CharField(blank=True, max_length=150, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('password_changed', models.BooleanField(default=False)),
                ('is_private', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('actor_name', models.CharField(blank=True, max_length=150, null=True)),
                ('actor_role', models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('id-staff', 'ID Staff'), ('user', 'User'), ('anonymous', 'Anonymous'), ('system', 'System')], default='anonymous', max_length=20)),
                ('action', models.CharField(max_length=120)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=255)),
                ('resource', models.CharField(blank=True, max_length=100, null=True)),
                ('resource_id', models.CharField(blank=True, max_length=50, null=True)),
                ('success', models.BooleanField(default=True)),
                ('status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='user_auditl_created_566317_idx'), models.Index(fields=['actor_role', '-created_at'], name='user_auditl_actor_r_7de8e2_idx'), models.Index(fields=['action', '-created_at'], name='user_auditl_action_f9a284_idx')],
            },
        ),
    ]
