# Generated by Django 6.0.3 on 2026-04-15 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
        ("auditlogs", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(name="AuditLog"),
                migrations.CreateModel(
                    name="AuditLog",
                    fields=[],
                    options={"proxy": True},
                    bases=("auditlogs.auditlog",),
                ),
            ],
        ),
    ]

