# Generated by Django 6.0.3 on 2026-03-31 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='alumni_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
